### ISSUE TITLE
Instructions and examples?

### ISSUE THREAD

**Issue by GeoffreyPlitt** [htbrown/rethinkdb-import#1]
When I run "node index", I see:
Please refer to the documentation (https://github.com/htbrown/rethinkdb-import) for instructions and an example of a valid JSON format.

But I don't see instructions or example JSON in this repo. Where are they?

**Comment by htbrown** [comment]
My apologies - this entire project completely slipped my mind. Will right some documentation today when I get a chance.

**Comment by htbrown** [comment]
Basic documentation in place.
